### ISSUE TITLE
Rebalance Drops

### ISSUE THREAD

**Issue by K4N0** [TeamDmfMM/StarvationAhoy#11]
For the size of the cow, there needs to be more meat dropped, Maybe 3 to 5.
I can balance how much hunger you get from the meat to make it work.
I'll be making all other items like berries 1/2 a hunger with no saturation to force players to cook their meat.

**Comment by K4N0** [comment]
Probably more leather also, 1 seems a bit odd.

**Comment by K4N0** [comment]
Feature Suggestion: Burnt meat can be turned into leather or ate for very low hunger.
I understand the mod is new and beta, I'm just spitting out ideas, close anything you don't like
it's fine. 
Will meat and food eventually go bad and turn into rotten flesh? unless kept in a freezer? or ice chest?

**Comment by dmf444** [comment]
Eventually, meat will rot. That's all in the plan.

**Comment by K4N0** [comment]
Will you add a config or add to the config what food should rot. I'd hate to see my medic kit from flan's rot.

**Comment by K4N0** [comment]
If you go throught the trouble of cooking a carcass on a spitfire roaster and have to time it right without burning it, it should give lots more food than if you cut it up and cook it in a furnace. To get players to want to roast the carcasses instead of just cutting it up. If you decide to add in body parts maybe it can give off bigger more filling parts from roasting it than chopping it up.
Edit. nah, same amount, you'll just have to cook the raw items before you can eat them.
