### ISSUE TITLE
Feature Suggestion: Include Sheep

### ISSUE THREAD

**Issue by K4N0** [TeamDmfMM/StarvationAhoy#13]
It would be nice to see sheep included same as the other animals.

**Comment by dmf444** [comment]
Sheep and rabbits will be included when we update to 1.8

**Comment by K4N0** [comment]
I might skip 1.8 all together, since it's already at 1.9

**Comment by mincrmatt12** [comment]
forge is not at 1.9 yet, and probably wont be for quite some time.

**Comment by K4N0** [comment]
ahh, yeah, forgot. I dunno if my modpack will make it to 1.8

**Comment by mincrmatt12** [comment]
it might. waiting till 1.8 as mutton was added then
