### ISSUE TITLE
No potion effects.

### ISSUE THREAD

**Issue by K4N0** [TeamDmfMM/StarvationAhoy#20]
I haven't checked the configs, but when i ate a god apple i received no potion effects. I removed your mod and i ate another apple and got the effects. Does this mod remove potion effects?

**Comment by K4N0** [comment]
I also wasn't able to increase my health beyond 10 hearts. On my server we can gain up to 30 red hearts and 10 yellow hearts (absorption).

**Comment by mincrmatt12** [comment]
interesring

were you using an enchanted golden apple?

**Comment by mincrmatt12** [comment]
nevermind. looking into it tonight, but i seem to remember not finishing golden apples.

**Comment by K4N0** [comment]
Yes, i ate a god apple made with gold blocks. i'll get some more info if you need.

**Comment by mincrmatt12** [comment]
no, we just forgot to do god apples. expect it soonish

**Comment by K4N0** [comment]
I have just been waiting for an update so i can do some more testing as you progress.
I'll make a mod showcase so you have something to place in the description. 
I'll make more videos as you progress.

**Comment by K4N0** [comment]
No worries, No rush.

**Comment by K4N0** [comment]
Is there a link for others to download the mod or is it too soon to release a version of it.
I understand it is a WIP mod but if they wanted to try it out do you have a link or should i 
put up the link you gave me? Or what link would you like for me to use to link them to your website or mod page? curse? Minecraft Forums? Or i can just link them to this Github page as well.

**Comment by dmf444** [comment]
Just need to finish a logo and I'll upload it to curse then you can release the video.

**Comment by K4N0** [comment]
Nice!!

**Comment by K4N0** [comment]
Just in case this is my modpack. I have put this together over the past year.
http://www.technicpack.net/modpack/mojangsters.583708
Comes with a server ip included.

**Comment by dmf444** [comment]
http://minecraft.curseforge.com/projects/starvation-ahoy this is live and you can download latest versions from here

**Comment by mincrmatt12** [comment]
fixed on my branch, should get put into curse soon.
