### ISSUE TITLE
Stick, Crash

### ISSUE THREAD

**Issue by K4N0** [TeamDmfMM/StarvationAhoy#22]
I placed 2 spit roast stands and as i was placing the stick between them when a player jumped on the stick and it caused him to crash. I'm guessing it was due to the multi block being created.

http://pastebin.com/jqCuWKQe

**Comment by K4N0** [comment]
This time it crashed again for the player, same crash report, but they did not jump on the stick. They were just standing about 2 blocks away from it. It did not crash for me.

His Quote:
"hey, There's something wrong with that stick, Man"

**Comment by mincrmatt12** [comment]
still have the world with you?

**Comment by K4N0** [comment]
sry for the late reply, i can make a new test world quickly. Holidays you know.

**Comment by K4N0** [comment]
let me know when you have a update for me to test out, i've just been waiting for a new jar file to test out.

**Comment by K4N0** [comment]
This mod will be great with one of my newest modpacks. It's called HardVanilla.
It's a post apocalyptic world where it rains Acid rain every time it rains. it killz everything including mobs and animals. Not trees, but yes to crops and such.

**Comment by mincrmatt12** [comment]
just use the newest jar right now

**Comment by K4N0** [comment]
oh ok, i just saw 1 download, so i thought it was an old one.
I'll test it when i get home.

**Comment by mincrmatt12** [comment]
Not to be pushy, but I've been waiting 2 weeks. Closing this if I don't get something in the next week

**Comment by K4N0** [comment]
Sorry, holiday stuff and family rolled over into january and i just lost track of what i was doing. I have a mod showcase made for you i just have to finish editing it. I'll upload a copy of what i have so far when i get home so you can look throught it and let me know if i missed anything. Here is my channel, pretty new, but it should come out nice. https://www.youtube.com/channel/UCVRDbrSypbA696FHcaiBhkg/videos?view=0&sort=dd&shelf_id=0

**Comment by mincrmatt12** [comment]
OK, sounds good.

**Comment by K4N0** [comment]
Fixed.
