### ISSUE TITLE
Lighting The Netherack

### ISSUE THREAD

**Issue by K4N0** [TeamDmfMM/StarvationAhoy#24]
To be able to light the netherrack underneath the spit roaster i need to set up the cooker like so.
Any ideas to be able to place it ground level, but still be able to light the netherrack?

![2015-11-02_20 35 57](https://cloud.githubusercontent.com/assets/10932905/10900817/d279ef28-81a1-11e5-98f8-9be1a09b4b1c.png)

**Comment by K4N0** [comment]
Actually i can do this,
![2015-11-02_20 50 46](https://cloud.githubusercontent.com/assets/10932905/10900927/741a2dce-81a3-11e5-868d-0080004d75bf.png)

**Comment by K4N0** [comment]
I can't light this. I would have to break the 2 blocks in front of it and go down 2 more.
![2015-11-02_20 52 32](https://cloud.githubusercontent.com/assets/10932905/10900941/ac0bdf8e-81a3-11e5-92b8-4169f94b58c1.png)

**Comment by K4N0** [comment]
I can't light this either. i would have to break the blocks in front of it.
![2015-11-02_20 54 01](https://cloud.githubusercontent.com/assets/10932905/10900956/e3c963a6-81a3-11e5-9a15-6f4dd77e428c.png)

**Comment by mincrmatt12** [comment]
this is actually a known issue with forge and bounding boxes. maybe i'll just set it up so that when you try and light the stick, it tries to light the blocks underneath it.
