### ISSUE TITLE
[1.9:] skinning pig / sheep carcass nets no leather / skins

### ISSUE THREAD

**Issue by kotoroshinoto** [TeamDmfMM/StarvationAhoy#30]
as the title states. Is it just following the vanilla drop tables?

Would think you'd actually get something, but its up to you.

**Comment by dmf444** [comment]
Pigs don't drop anything, but sheep should drop wool

**Comment by kotoroshinoto** [comment]
yeah, so its following the ideas laid down by vanilla mechanics.

Doesn't this render the pig skinning to be mostly busywork then?

is there an inherent reason we couldn't just toss the pig carcass directly onto the spit if there is no item production from the corpse?

**Comment by kotoroshinoto** [comment]
Or is there an api that allows for drops to be added and this is necessary as a placeholder?

**Comment by dmf444** [comment]
It's necessary for the api to work. All animals run through it and it needs to a skinning step

**Comment by kotoroshinoto** [comment]
No problem then. Its not a big deal and its pretty straightforward, just wanted to make sure.

**Comment by dmf444** [comment]
The cooking blocks are the invisible blocks that get placed when the multi block is put together. They go between the Spitroast.
