### ISSUE TITLE
[1.9] meat roasting supports + stick create multi-block but does not place cooker blocks

### ISSUE THREAD

**Issue by kotoroshinoto** [TeamDmfMM/StarvationAhoy#31]
it was a known bug as you said, but I figured I should create an issue for it nonetheless.
Some notes I made while looking at the code are in https://github.com/TeamDmfMM/StarvationAhoy/issues/29

Another thing of note, if I use the /give command to hand the cooker block item to myself, I find that I cannot place them. That might be normal and expected, but I figured it warranted mentioning.

**Comment by dmf444** [comment]
Fixed and released

**Comment by kotoroshinoto** [comment]
purely out of curiosity, what changes in which files fixed this issue?

I just want to understand in case I run across this kind of thing again.
