### ISSUE TITLE
crash upon startup

### ISSUE THREAD

**Issue by lag42** [TeamDmfMM/StarvationAhoy#44]
using the latest version and in phase 2 of loading and it appears to only be vanilla and your code
[crash-2017-12-15_08.22.26-client.txt](https://github.com/TeamDmfMM/StarvationAhoy/files/1563002/crash-2017-12-15_08.22.26-client.txt)

**Comment by dmf444** [comment]
Well that’s new. I’ll take a look at it

**Comment by dmf444** [comment]
Fixed in 2.10
