### ISSUE TITLE
Crash when right-clicking roaster

### ISSUE THREAD

**Issue by dmf444** [TeamDmfMM/StarvationAhoy#8]
Where should i post the uhmm crash reports
http://pastebin.com/bRNFTwzx

placed 2 spit roast stands, 2 blocks apart and placed a stick on it, it created the roater thingy just fine.
 I then right clicked the handle without any dead animal on yet and i crashed.

**Comment by K4N0** [comment]
The dead skinned cow has to be cooked first before it can be chopped up into edible food right?

**Comment by dmf444** [comment]
Once you roast a skinned cow, you cut it off with a butcher's knife and it will break into steak. Same goes for pigs and chickens

**Comment by K4N0** [comment]
I like that it spins on it's own when fire is placed.

**Comment by K4N0** [comment]
How do you know when it's cooked? not that far yet?
edit, never mind

**Comment by K4N0** [comment]
That is so cool, The cow just sits there on the ground until you pick it up.

**Comment by K4N0** [comment]
Confirm it's fixed.
